version: '3.3'
services:
  webapp:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: webapp
    working_dir: /usr/src/app
    env_file:
      - .env
    ports:
      - 9090:9090
    volumes:
      - ./:/usr/src/app:rw
    command: "yarn develop"
