version: '3.3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    working_dir: /usr/src/app/backend
    container_name: backend
    networks:
      - node-webapp-network
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app/backend:rw
    command: "sh -c 'yarn && yarn start:dev'"
    
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: frontend
    working_dir: /usr/src/app/frontend
    env_file:
      - ./frontend/.env
    networks:
      - node-webapp-network
    ports:
      - 9090:9090
    volumes:
      - ./frontend:/usr/src/app/frontend:rw
    command: "sh -c 'yarn && yarn develop'"

networks:
  node-webapp-network:
    driver: bridge
