version: '3.3'
services:
  restapp:
    build: .
    container_name: restapp
    working_dir: /usr/src/app
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app:rw
    command: "yarn start:dev"
